basePath: /
consumes:
- application/json
definitions:
  ERD:
    description: ERD defines the structure of an API ERD
    properties:
      actions:
        description: 'the actions a user can perform with this ERD. will be a subset
          of: [read, write, publish, subscribe]'
        items:
          type: string
        type: array
        x-go-name: Actions
      address:
        description: the address of this ERD as a hex string
        type: string
        x-go-name: Address
      fields:
        description: the fields an ERD response will contain. each must contain the
          ERD name either as the entire field name or as a prefix
        items:
          type: string
        type: array
        x-go-name: Fields
      id:
        description: the id for this ERD
        format: int64
        minimum: 0
        type: integer
        x-go-name: ID
      name:
        description: the name of this ERD
        type: string
        x-go-name: Name
    required:
    - name
    - address
    - fields
    type: object
    x-go-package: github.com/andrewmathies/msl/data
info:
  description: Documentation for ERD API
  title: ERD API
  version: 0.0.1
paths:
  /erds:
    get:
      description: Returns a list of erds
      operationId: listERDs
      responses:
        "200":
          $ref: '#/responses/erdsResponse'
      tags:
      - erds
  /erds/{id}:
    delete:
      description: Delete an ERD
      operationId: deleteERD
      parameters:
      - description: The id of the ERD to remove from the data store
        format: int64
        in: path
        name: id
        required: true
        type: integer
        x-go-name: ID
      responses:
        "201":
          $ref: '#/responses/noContent'
      tags:
      - erds
produces:
- application/json
responses:
  erdsResponse:
    description: A list of ERDs in the response
    schema:
      items:
        $ref: '#/definitions/ERD'
      type: array
  noContent: {}
schemes:
- http
swagger: "2.0"
